spring.jpa.database=MYSQL
spring.datasource.url=jdbc:mysql://localhost/granapi?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.date-format=dd/MM/yyyy

logging.level.com.grana-api.api=DEBUG

grana-api-property.mail.host =smtp.office365.com
grana-api-property.mail.port =587
grana-api-property.mail.username=********@******.com
grana-api-property.mail.password=**********

grana-api-property.awsS3.accessKeyId=${S3_ACCESSKEY}
grana-api-property.awsS3.secretAccessKey=${S3_SECRETACCESS}
